# Generated by Django 2.1.15 on 2021-05-18 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_fanfics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fandom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fandom_author', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='fanfic',
            old_name='text',
            new_name='annotation',
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='register_date',
            field=models.DateField(default='1970-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fanfic',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_fanfics.Author'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='fanfic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_fanfics.Fanfic'),
        ),
        migrations.AddField(
            model_name='fanfic',
            name='fandom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='app_fanfics.Fandom'),
        ),
    ]
