# Generated by Django 2.1.15 on 2021-05-24 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_fanfics', '0002_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
    ]
