# Generated by Django 2.1.15 on 2021-05-26 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fanfics', '0003_remove_author_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter_title',
            field=models.CharField(default='Глава <django.db.models.fields.IntegerField>', max_length=500),
        ),
        migrations.AddField(
            model_name='chapter',
            name='publication_date',
            field=models.DateTimeField(default=datetime.date(2021, 5, 26), verbose_name='Published:'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='text',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='fanfic',
            name='publication_date',
            field=models.DateTimeField(default=datetime.date(2021, 5, 26), verbose_name='Published:'),
        ),
    ]
